server:
  servlet:
    context-path: /spring
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://157.179.132.254:3306/sample
    username: root
    password: mobile
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    th.in.lordgift.SpringBoot2Tutorial.*: debug
